### ISSUE TITLE
后端请求失败

### ISSUE THREAD

**Issue by simpleYOTO** [ZYKsslm/nonebot_plugin_zyk_novelai#1]
大佬，我的请求后输出的是“后端请求失败”，是我的env设置格式有问题吗，恳请大佬指正.
这是我的设置:
novelai_post_url = "https://********-stevens.trycloudflare.com/"
novelai_proxy_port = "*****"

**Comment by ZYKsslm** [comment]
首先先确认你的版本是否为最新版本

**Comment by ZYKsslm** [comment]
> 首先先确认你的版本是否为最新版本

最新版本为2.3，装了老版本的需重装

**Comment by ZYKsslm** [comment]
失败原因是什么？

**Comment by simpleYOTO** [comment]
有一个警告:Unsupported upgrade request
还有错误就是:后端请求失败

**Comment by ZYKsslm** [comment]
分别截一下
1.报错截图
2.check state的后端状态截图
3.你的插件版本截图

**Comment by simpleYOTO** [comment]
<img width="324" alt="39f7fe09a8430dbc0c779e19c2e21e4" src="https://user-images.githubuse
<img width="214" alt="76278a6303fc5aa6230f5b858dfc3d1" src="https://user-images.githubusercontent.com/107185219/204078152-03d20005-00cf-4cd5-890b-89f5f4af7d6c.png">
rcontent.com
<img width="320" alt="d8589f97133d38b209bd5a5187dd918" src="https://user-images.githubusercontent.com/107185219/204078155-43ad3c0c-17de-404b-97eb-aac46d07203e.png">
/107185219/204078147-a48e1267-d8ca-42ac-a844-c675eb4f4ae6.png">

大佬，我现在不是很清楚这个代理端口，会不会是这个原因，因为没学过这些方面的，麻烦大佬指教

**Comment by simpleYOTO** [comment]
<img width="324" alt="39f7fe09a8430dbc0c779e19c2e21e4" src="https://user-images.githubusercontent.com/107185219/204078243-e239858d-ea84-44c5-b9cd-d093623f1311.png">

错误好像没发错来，我补发一下

**Comment by simpleYOTO** [comment]
我之前是代理端口是用bot的端口，但是好像没有用，不是很理解代理端口

**Comment by ZYKsslm** [comment]
是本地端口的原因

**Comment by ZYKsslm** [comment]
本地端口指的是你代理走的端口

**Comment by ZYKsslm** [comment]
![image](https://user-images.githubusercontent.com/110616928/204081019-3d69edd8-58e1-4d9b-af75-678b339e8029.png)

**Comment by ZYKsslm** [comment]
先确保你开了梯子，再设置端口

**Comment by ZYKsslm** [comment]
OK我已经在文档里提了

**Comment by simpleYOTO** [comment]
感谢大佬！是这个问题
