### ISSUE TITLE
我想使用自己部署的novelai请问怎么设置

### ISSUE THREAD

**Issue by QwindF** [ZYKsslm/nonebot_plugin_zyk_novelai#10]
我想使用自己部署的novelai请问怎么设置，用的是b站up主：[秋葉aaaki](https://space.bilibili.com/12566101)的，已经看眼在web上正常工作

**Comment by ZYKsslm** [comment]
正常使用就好了，url使用本地的，但不用设置代理（无代理模式）

**Comment by QwindF** [comment]
http://吧，类似是在env里填这个吗
novelai_post_url = http://127.0.0.1:7860/

**Comment by QwindF** [comment]
![image](https://user-images.githubusercontent.com/87116340/209461127-376c318e-b5a8-4225-ae79-152b4c9317fa.png)

**Comment by QwindF** [comment]
但是 `[ERROR] nonebot_plugin_zyk_novelai | 后端请求失败:{"detail":"Not Found"}`

**Comment by QwindF** [comment]
![image](https://user-images.githubusercontent.com/87116340/209461251-615ecfb1-a64f-45e2-afea-4d12e12a72e5.png)

**Comment by ZYKsslm** [comment]
我打了一长串还没发就看到你这张图，喂喂兄弟这是Web-UI不是Naifu啊

**Comment by QwindF** [comment]
()草，我一直以为这两是一个东西

**Comment by QwindF** [comment]
不过还是谢谢你qwq
