### ISSUE TITLE
链接会变，而且过一段时间就失效了

### ISSUE THREAD

**Issue by purelolly** [ZYKsslm/nonebot_plugin_zyk_novelai#11]
谷歌Colab模型启动后生成的链接会变，而且过一段时间就失效了

**Comment by TomorrowLost** [comment]
![}SS74WXZ5I%@(~YZ84EU17F](https://user-images.githubusercontent.com/78009999/209785220-6b69ea1e-6c97-4fa6-a758-3169238745cc.png)
![Uploading E21PBANK61D_3K(4PQPO6RA.
![E26W)0XI@XTHTZ226O$0HR5](https://user-images.githubusercontent.com/78009999/209785234-65b675e5-30bc-45ef-a230-4e22a81c10e4.png)
png…]()

**Comment by ZYKsslm** [comment]
应该是代理的问题，你本地代理端口设置了么

**Comment by ZYKsslm** [comment]
> > 应该是代理的问题，你本地代理端口设置了么
> 
> ![image](https://github.com/ZYKsslm/nonebot_plugin_zyk_novelai/assets/76981036/dd6f43bc-afe1-4348-b328-0bf97db6e9d7)
> 大佬 这是什么问题?

为你的机器人设置昵称NICKNAME就好了
