### ISSUE TITLE
为什么AI画的全是涩图啊

### ISSUE THREAD

**Issue by MChongshi** [ZYKsslm/nonebot_plugin_zyk_novelai#12]
![3390d4e71a7bd294](https://user-images.githubusercontent.com/66892697/218247424-0314c76c-24ce-4965-abdf-b8f27badf49c.png)

**Comment by ZYKsslm** [comment]
那你自己写prompt啊，数据库里的tag都不太正经…

**Comment by ZYKsslm** [comment]
会考虑更新数据库，你也可以把resource目录下的db数据库替换掉，不过要sqlite3
