### ISSUE TITLE
报错 all connection attempts failed

### ISSUE THREAD

**Issue by Big-Smart-h** [ZYKsslm/nonebot_plugin_zyk_novelai#16]
一直报错后端请求失败该怎么办？
![屏幕截图](https://github.com/ZYKsslm/nonebot_plugin_zyk_novelai/assets/78341556/32b03d14-f68f-490a-89ff-b6db7932532d)

**Comment by ZYKsslm** [comment]
可能是你代理的问题

**Comment by Big-Smart-h** [comment]
ubuntu应该怎么代理啊，我是在.bashrc里加了http_proxy=http://localhost:10809

**Comment by ZYKsslm** [comment]
请看README手动配置本地代理端口
