### ISSUE TITLE
有点复杂繁琐

### ISSUE THREAD

**Issue by luoguixin** [ZYKsslm/nonebot_plugin_zyk_novelai#2]
虽然很简单了

**Comment by ZYKsslm** [comment]
请问是哪里复杂了呢

**Comment by luoguixin** [comment]
就获取url那里

**Comment by ZYKsslm** [comment]
在Colab中按照步骤运行代码块，耐心等待几分钟（一般不到10分钟），就能看见生成的URL

**Comment by luoguixin** [comment]
我没有这个界面

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204290858-7cfcd447-c4ee-45e4-bcd6-229248fd93e4.png)

**Comment by luoguixin** [comment]
这里对吧

**Comment by luoguixin** [comment]
然后点旁边那个运行对吧

**Comment by ZYKsslm** [comment]
依次运行代码块

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204292822-45d55984-c14c-4a28-9551-ea155c064aa4.png)

**Comment by luoguixin** [comment]
这样吗？

**Comment by ZYKsslm** [comment]
是的

**Comment by luoguixin** [comment]
代理怎么弄？

**Comment by ZYKsslm** [comment]
看README

**Comment by luoguixin** [comment]
不理解

**Comment by luoguixin** [comment]
明白了

**Comment by ZYKsslm** [comment]
现在能否正常使用插件呢

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204295476-8beb2c64-62ca-4de7-9fe1-dae05cc345c1.png)

**Comment by luoguixin** [comment]
我安装一下

**Comment by luoguixin** [comment]
有一个无法触发

**Comment by ZYKsslm** [comment]
可能是你的指令没使用正确，请仔细阅读README后再提交issue

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204297457-01f99560-4838-48e9-9330-8133b32bb69c.png)

**Comment by luoguixin** [comment]
我复制的指令

**Comment by ZYKsslm** [comment]
嗯，是跟其他插件冲突了呢

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204297786-a7dd2be0-441f-4406-b3b9-e82bf0805162.png)

**Comment by ZYKsslm** [comment]
被其他插件阻断了，这种情况只能把那个插件卸载了

**Comment by luoguixin** [comment]
好的

**Comment by ZYKsslm** [comment]
末尾加上/

**Comment by ZYKsslm** [comment]
现在插件可以正常使用了么

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204299590-1d921fd2-6f96-483c-a8f8-5380c0d91a1e.png)

**Comment by luoguixin** [comment]
没触发

**Comment by ZYKsslm** [comment]
兄弟你没卸载吗，还是被其他插件拦截触发了
![image](https://user-images.githubusercontent.com/110616928/204299959-2ff40a55-f364-40a2-9051-438c93a16c1e.png)

**Comment by luoguixin** [comment]
卸载了

**Comment by luoguixin** [comment]
刚刚冲突那个

**Comment by ZYKsslm** [comment]
那我也没有解决办法，插件被其他的Matcher抢了

**Comment by ZYKsslm** [comment]
或许你可以重新创建一个机器人

**Comment by luoguixin** [comment]
好的
