### ISSUE TITLE
好像后端问题

### ISSUE THREAD

**Issue by luoguixin** [ZYKsslm/nonebot_plugin_zyk_novelai#4]
![image](https://user-images.githubusercontent.com/114066432/204310224-eb050582-6e97-4852-ae36-7e303639c25b.png)

**Comment by ZYKsslm** [comment]
已经关闭的issue中有一个情况跟你一样的，你去看看

**Comment by luoguixin** [comment]
![image](https://user-images.githubusercontent.com/114066432/204312802-ef43787c-d30c-43eb-acac-bd5d6d4e3e64.png)

**Comment by ZYKsslm** [comment]
可能是你的代理的问题，这种情况我也没有遇到过。你可以换一个代理软件或者是你的本地代理端填错了

**Comment by luoguixin** [comment]
我看了没填错，就是连不上，显示请求失败

**Comment by ZYKsslm** [comment]
暂时无法解决

**Comment by ZYKsslm** [comment]
排除完了，是你后端的问题
