### ISSUE TITLE
后端提示Name or service not known

### ISSUE THREAD

**Issue by DUNKILL** [ZYKsslm/nonebot_plugin_zyk_novelai#5]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/91525837/204431157-26fe0861-f19c-4c90-a711-7c60cfac9e14.png">

用check state观察到后端地址为：xxx.trycloudflare.com/generate-stream，然后浏览器打开这个页面实际上是404的，服务器ping这个域名可以ping通，网络没有问题，是不是后端地址的规则需要修改？

**Comment by DUNKILL** [comment]
> 网页中打开失败是正常的，因为那是生成图片的接口。而你输入的URL是NovelAI的前端地址，那个是可以打开的。 你分别截一下：
> 
> 1. check state配置信息截图
> 2. Colab部署状态截图

![image](https://user-images.githubusercontent.com/91525837/204682240-ed1d22b3-3c58-4622-b65e-b365872d2a3f.png)
![image](https://user-images.githubusercontent.com/91525837/204682358-cd0fe396-8e0c-4777-84d5-08cb1925194a.png)
![image](https://user-images.githubusercontent.com/91525837/204682416-698570f8-fab0-40b8-941c-0bb1a26df115.png)

**Comment by ZYKsslm** [comment]
插件版本是最新版的么，有可能是老版本的BUG

**Comment by ProblemFactory** [comment]
是proxy的问题，当配置文件中不设置port（也就是port为None）的时候，插件不会走setport流程，而是会设置http://127.0.0.1:None作为http(s)代理。这个信息会被传递到get_data的proxies参数，导致无法解析和访问任何URL。

**Comment by ZYKsslm** [comment]
> 是proxy的问题，当配置文件中不设置port（也就是port为None）的时候，插件不会走setport流程，而是会设置http://127.0.0.1:None作为http(s)代理。这个信息会被传递到get_data的proxies参数，导致无法解析和访问任何URL。

嗯，确实如此。直接在env中设置而没有使用set_port指令的话确实无法识别，是个BUG

**Comment by ZYKsslm** [comment]
感谢指正，:bug: BUG已修复

**Comment by ProblemFactory** [comment]
hmmm port还有可能是None，比如配置文件里没写的情况

**Comment by ZYKsslm** [comment]
嗯，其实是之前觉得省事懒得写try模块

**Comment by ZYKsslm** [comment]
> 嗯，其实是之前觉得省事懒得写try模块

算了，还是一并加上吧

**Comment by ProblemFactory** [comment]
新版本还是有问题，因为`int(None)`出现的exception是`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`而不是ValueError。这现在会直接导致无法加载。

**Comment by ZYKsslm** [comment]
> 新版本还是有问题，因为`int(None)`出现的exception是`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`而不是ValueError。这现在会直接导致无法加载。

并不会，读取全局配置为None只会是str类型而不是NoneType类型，所以不会报错

**Comment by ProblemFactory** [comment]
我的意思是在全局配置里没有写相应条目，不是设置为了"None"，此时读到的是NoneType。不过没事了，我查了下是我用的nonebot是修改版，有些行为和官方版本不太一样。
