### ISSUE TITLE
非Windows系统下读取数据库失败导致随机tag无法生成

### ISSUE THREAD

**Issue by ProblemFactory** [ZYKsslm/nonebot_plugin_zyk_novelai#6]
错误提示是`sqlite3.OperationalError: no such table: main_tags`，原因是work.py里使用了`db_path = os.path.abspath(os.path.dirname(__file__)) + r"\resource\novelai_tags.db"`生成数据库路径，而在非Windows系统下`'\'`并不是路径分隔符。
推荐使用`db_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), "resource","novelai_tags.db")`来合并路径。

**Comment by ProblemFactory** [comment]
另外建议生成随机tag的时候最好把tag也发送出来。。。

**Comment by ZYKsslm** [comment]
> 另外建议生成随机tag的时候最好把tag也发送出来。。。

生成的时候tag会显示

**Comment by ProblemFactory** [comment]
> > 另外建议生成随机tag的时候最好把tag也发送出来。。。
> 
> 生成的时候tag会显示

但是只会显示在后台，我的意思是作为消息发送出来

**Comment by ZYKsslm** [comment]
好的

**Comment by ZYKsslm** [comment]
已修改
